### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by MortalCatalyst** [rgbkrk/atom-script#283] opened 2015-02-11 10:24 UTC
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/opt/atom/resources/app/src/atom.js:54:11)
ScriptView.initialize (/home/sayth/.atom/packages/script/lib/script-view.coffee:26:9)
```

**Comment by erran** [comment] 2015-02-11 14:41
This is a duplicate of #266. See #278 which is waiting to be tested by a second contributor before merging and pushing.

**Closed by erran** 2015-02-11 14:41 UTC
