### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by souzaonofre** [rgbkrk/atom-script#279] opened 2015-02-01 11:39 UTC
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/opt/atom/resources/app/src/atom.js:53:11)
ScriptView.initialize (/home/onofre/.atom/packages/script/lib/script-view.coffee:28:9)
```

**Comment by rgbkrk** [comment] 2015-02-01 16:09
Closing as duplicate of #266.

**Closed by rgbkrk** 2015-02-01 16:09 UTC
