### ISSUE TITLE
'Run only selected code' does not work for me (JS)

### ISSUE THREAD

**Issue by dengayevskiy** [rgbkrk/atom-script#324] opened 2015-03-08 23:32 UTC
When i select some code in my .js file and press 'ctrl-shift-b' empty console appears with only info about time that executing took ([Finished in 0.138s]). But when nothing is selected everything works fine.

**Comment by erran** [comment] 2015-03-13 01:03
@dengayevskiy could you provide a code example that reproduces this issue? A quick hello world works for me.

```javascript
```

**Comment by dengayevskiy** [comment] 2015-03-17 14:06
For me even `console.log("hello world");` does not work. It gives me empty console with only time finished.

**Comment by rgbkrk** [comment] 2015-03-17 18:05
Create a `.sh` script that runs `env`. In particular, check out what PATH is. Also, try `which node`.

**Comment by claudiojs** [comment] 2017-05-24 08:40
Run selection for JavaScript doesn't work for me either (empty console, only time elapsed appears). Without selection it runs correctly. Also run selection for PHP works fine. What exactly should I check if I run `env ` / `which node` in a `.sh` file?

**Comment by rgbkrk** [comment] 2017-05-24 08:42
What's the code you're running?

**Comment by claudiojs** [comment] 2017-05-24 15:06
Nothing special:
// Test 1
`console.log('foobar');`

// Test 2
`var foo = 'bar';`
`console.log(foo);`

**Comment by danielbayley** [comment] 2017-10-10 17:26
@dengayevskiy @claudiojs Try again with the latest update.

**Comment by claudiojs** [comment] 2017-10-11 11:51
After the last update (3.15.0):
- Running JS scripts (selecting a line or not) throws an error: "The command "bash" could not be found".
- Executing php scripts works well.

**Comment by danielbayley** [comment] 2017-10-11 12:45
@claudiojs So, therefore, you have `php` somewhere on your `PATH`, but not `bash`. Are you on Windows?

**Comment by claudiojs** [comment] 2017-10-11 13:36
Correct, Windows 10.

**Comment by danielbayley** [comment] 2017-10-11 14:57
@claudiojs Ah ok, well JavaScript (and CoffeeScript) grammars are now using `bash -c 'babel …' | node` (piping the output of `babel` into `node`) to take advantage of the Babel configuration [set up especially to target Atom] within this package instead of having to set it up locally for every project or worse, globally. This gets around the limitations of the previous `babel-node` approach, and also doesn't alter the current working directory for the actual code being run. I thought `bash` was supported on Windows now?

**Comment by claudiojs** [comment] 2017-10-11 16:04
Not yet.

**Comment by danielbayley** [comment] 2017-10-13 01:52
@claudiojs Fixed in #1451.

**Closed by danielbayley** 2017-10-13 01:52 UTC

**Comment by claudiojs** [comment] 2017-10-13 10:22
Perfect, thank you!
