### ISSUE TITLE
Add Selection Based support for Java

### ISSUE THREAD

**Issue by veve1234** [rgbkrk/atom-script#904] opened 2016-04-24 12:25 UTC
##### Platform: `win32`
---
Unable to run a java program using script on atom. Displays that "Selection based runner not available for java"

**Comment by hazefor** [comment] 2016-07-01 07:10
I am having the same issue and looking for solution

**Comment by andyrichardson** [comment] 2016-10-28 09:52
Duplicate of #796

**Closed by andyrichardson** 2016-10-28 09:52 UTC
