### ISSUE TITLE
C++ cin [not working]

### ISSUE THREAD

**Issue by CamrynD** [rgbkrk/atom-script#1212] opened 2017-01-13 18:06 UTC
The Output window will not allow a ".cpp" file to take inputs from the user.

an example:
`cin >> anything;`
The Code stops there and waits for input.

works fine with python. Would be great if this could be fixed, this Package saves a lot of much time.

**Comment by rgbkrk** [comment] 2017-01-13 18:25
Thank you for reporting. We don't support stdin and no one is working on supporting it. Closing as duplicate of #385.

**Closed by rgbkrk** 2017-01-13 18:25 UTC
Labels: REPL/STDIN request
