### ISSUE TITLE
Command not configured for JavaScript (JSX)!

### ISSUE THREAD

**Issue by dev-xdyang** [rgbkrk/atom-script#919] opened 2016-05-11 14:07 UTC

**Comment by dudeinthemirror** [comment] 2016-07-03 03:42
Getting the same error (Atom 1.8.0).
Also tried:
```
/*esnext: true */
/*jshint esversion: 6 */
```
to no avail.

**Comment by andyrichardson** [comment] 2017-01-02 18:03
Duplicate of #630

**Closed by andyrichardson** 2017-01-02 18:03 UTC
