### ISSUE TITLE
Add support for HTML

### ISSUE THREAD

**Issue by andromeda306** [rgbkrk/atom-script#330] opened 2015-03-14 23:52 UTC
Hello,

I've recently started to delve into javascript and html development (complete novice) learning through Codeacademy and books/online. Lately I've been searching for a way to preview scripts I've made either off the cuff or copied from some of the Codeacademy activities and thought this package might do the trick.
But I've run into a problem, whenever I try and run my code in using the Run script I receive the error "Command not configured for HTML".

Could anyone please offer some advice as to how to fix this. I've noticed there is a configuration panel in the Packages/Script menu but I'm not sure what to enter.

Appreciate your help!

**Comment by rgbkrk** [comment] 2015-03-17 18:07
We're built on the idea that we can run the entire file as if it was a single script with text output. If you want a preview for your HTML page, try out https://atom.io/packages/atom-html-preview.

**Comment by erran** [comment] 2015-05-03 21:13
> @freeplanets001 What do you have in mind? For HTML I'd recommend using Atom's built in "Markdown preview" feature. It will render regular HTML files in addition to Markdown.

@andromeda306 @paravatee

**Comment by EntilZha** [comment] 2016-02-12 07:47
Closing as duplicate of #724, this issue was first, but the other has better discussion

**Closed by EntilZha** 2016-02-12 07:47 UTC
Labels: question
