### ISSUE TITLE
issue. java weird problem

### ISSUE THREAD

**Issue by My-** [rgbkrk/atom-script#1249] opened 2017-02-11 14:15 UTC
Then I run my code using script (Ctrl + Shift + B) it feels like then Atom runs code it gets stuck in one part, inside the loop (do/while or while). But it runs without any problem if I run in Atoms shell (using "javac test.java" and next "java test" commands).
Code:
 
```
import java.util.Scanner;

public class test{

  public static void main(String[] args) {
    Scanner input = new Scanner(System.in);
    int userInput = 0;

    System.out.println("-Before loop-");
    do{
      System.out.println(">We are inside loop<");

      // Problem starts here
      System.out.print("\nEnter number: ");    // <<<<<<<<<<<<<<< problem starts here
      userInput = input.nextInt();      // << if comment this line. Code runs as expected.

    }while (userInput < 2);

    System.out.println("\n-After loop-");
  }
}
```
I run this code without problem in Intellij IDEA , TextPad.

**Comment by andyrichardson** [comment] 2017-02-11 16:47
I'm pretty sure atom-script doesn't support command line input for Java.

**Comment by rgbkrk** [comment] 2017-02-11 17:32
Closing as duplicate of #385.

**Closed by rgbkrk** 2017-02-11 17:32 UTC
Labels: REPL/STDIN request
