### ISSUE TITLE
VERY long time

### ISSUE THREAD

**Issue by RealSlimRosey** [rgbkrk/atom-script#1389] opened 2017-07-21 09:39 UTC
Hi there,
I am an aspiring student who is starting to learn python and code as programming and game development is a passion I would like to pursue. I am following a python start up guide (here: [https://www.youtube.com/watch?v=DjEuROpsvp4&feature=youtu.be](url)). The person in the video recommends that I download your program. I followed the steps he did and installed the package, he ran his example script using cmd-i and it worked almost instantly. however, when I used it to run my test script, it just has an hourglass at the bottom of my screen and it has stayed like that for the past 30 minutes. Have I done something wrong? 
If it helps, I will give you the code I am running:
`a = int(input('Enter a number: '))
a = ('_')*a
print("^" + str(a) + "^")`
I also recently downloaded python 3.6.2 and downloaded another package called python-debugger ([https://atom.io/packages/python-debugger](url)).
I am also running Script version 3.15.0 and Atom 1.18.0 x64.
Any help would be greatly appreciated.
Thanks! Max

**Comment by mita4829** [comment] 2017-07-22 23:18
The reason for this is your code request input from the user. `input('Enter a number: ')`. To my knowledge, atom-script doesn't take in inputs, _correct me if I'm wrong_. You'll have to run your python code through terminal.

**Comment by rgbkrk** [comment] 2017-07-23 15:03
Atom script doesn't support stdin (requesting input) and I don't have time to implement it.

Try [Hydrogen](https://nteract.io/atom) instead or use a plain terminal.

Duplicate of #385

**Closed by rgbkrk** 2017-07-23 15:03 UTC
Labels: REPL/STDIN request
