### ISSUE TITLE
WorkspaceView.prependToTop is deprecated.

### ISSUE THREAD

**Issue by dimitrioschr** [rgbkrk/atom-script#432] opened 2015-05-07 20:12 UTC
Please use Workspace::addTopPanel() instead
```
WorkspaceView.prependToTop (/Applications/Atom.app/Contents/Resources/app/src/workspace-view.js:136:7)
ScriptOptionsView.initialize (/Users/dimitrios/.atom/packages/script/lib/script-options-view.coffee:51:23)
```

**Comment by rgbkrk** [comment] 2015-05-08 21:03
Dupe of #377, fixed in #407, upgrade to release 2.21.0.

**Closed by rgbkrk** 2015-05-08 21:03 UTC
