### ISSUE TITLE
Can't enter values through console when using raw_input() in Python

### ISSUE THREAD

**Issue by vmalyi** [rgbkrk/atom-script#494] opened 2015-07-02 09:25 UTC
I have a python script which processes user input with help of following code block:

``` 
def process_user_input():
    print('Enter text')
    sys.stdout.flush()
    user_input = raw_input()
    ...
```

When I start this script with help of CTRL+SHIFT+B in Atom editor, it runs but I'm unable to enter any values in the console.

Environment:
Win7x64
Atom 1.0.0
script@2.26.1

**Comment by rgbkrk** [comment] 2015-07-02 17:58
We don't handle STDIN sadly. We'd need someone to add support. Closing as duplicate of #73, #280 #385.

**Closed by rgbkrk** 2015-07-02 17:58 UTC
