### ISSUE TITLE
Add File Based support for C  

### ISSUE THREAD

**Issue by TemetNosce95** [rgbkrk/atom-script#508] opened 2015-07-14 04:03 UTC
##### Platform: `linux`
---How can I add support for C?

**Comment by rgbkrk** [comment] 2015-07-17 20:45
We'd need a way to pass in a file and run it for c. Have you tried `clang`?

**Comment by EntilZha** [comment] 2016-02-12 07:10
Duplicate of #454

**Closed by EntilZha** 2016-02-12 07:10 UTC
