### ISSUE TITLE
Add support for CSS

### ISSUE THREAD

**Issue by Euthpic** [rgbkrk/atom-script#1214] opened 2017-01-14 09:57 UTC
body {
    background-color: #1e1e1e;
}

.center {
    text-align: center;
    padding: 60px;
}

#MonValley #BrightDoor {
    transition: all 0.3s ease-in-out;
    opacity: 0;
}

#MonValley:hover #BrightDoor {
    opacity: 1;
}

#MonValley #Step1 {
    transition: all .65s ease-in-out;
    transform: translate(0px, 132px);
}

#MonValley:hover #Step1 {
    transform: translate(0px, 0px);
}

#MonValley #Step2 {
    transition: all .6s ease-in-out;
    transform: translate(0px, 132px);
}

#MonValley:hover #Step2 {
    transform: translate(0px, 0px);
}

#MonValley #Step3 {
    transition: all .55s ease-in-out;
    transform: translate(0px, 132px);
}

#MonValley:hover #Step3 {
    transform: translate(0px, 0px);
}

#MonValley #Step4 {
    transition: all .5s ease-in-out;
    transform: translate(0px, 132px);
}

#MonValley:hover #Step4 {
    transform: translate(0px, 0px);
}

#MonValley #Step5 {
    transition: all .45s ease-in-out;
    transform: translate(0px, 132px);
}

#MonValley:hover #Step5 {
    transform: translate(0px, 0px);
}

#MonValley #Step6 {
    transition: all .4s ease-in-out;
    transform: translate(0px, 132px);
}

#MonValley:hover #Step6 {
    transform: translate(0px, 0px);
}

#MonValley #Step7 {
    transition: all .35s ease-in-out;
    transform: translate(0px, 132px);
}

#MonValley:hover #Step7 {
    transform: translate(0px, 0px);
}

#MonValley #Step8 {
    transition: all .3s ease-in-out;
    transform: translate(0px, 132px);
}

#MonValley:hover #Step8 {
    transform: translate(0px, 0px);
}

#MonValley #Step9 {
    transition: all .25s ease-in-out;
    transform: translate(0px, 132px);
}

#MonValley:hover #Step9 {
    transform: translate(0px, 0px);
}

#MonValley #Step10 {
    transition: all .2s ease-in-out;
    transform: translate(0px, 132px);
}

#MonValley:hover #Step10 {
    transform: translate(0px, 0px);
}

#MonValley #Step11 {
    transition: all .15s ease-in-out;
    transform: translate(0px, 132px);
}

#MonValley:hover #Step11 {
    transform: translate(0px, 0px);
}

#MonValley #Step12 {
    transition: all .1s ease-in-out;
    transform: translate(0px, 132px);
}

#MonValley:hover #Step12 {
    transform: translate(0px, 0px);
}

#MonValley #Step13 {
    transition: all .05s ease-in-out;
    transform: translate(0px, 132px);
}

#MonValley:hover #Step13 {
    transform: translate(0px, 0px);
}

**Comment by nixel2007** [comment] 2017-01-14 12:11
How you want to run css?

**Comment by danielbayley** [comment] 2017-10-06 14:55
Duplicate of #1284

**Closed by danielbayley** 2017-10-06 14:55 UTC
