### ISSUE TITLE
can not run script

### ISSUE THREAD

**Issue by Niefee** [rgbkrk/atom-script#1450] opened 2017-10-12 02:52 UTC
environment:
OS: windows10 64bit
atom: 1.21.0
atom-script: 3.17.1
try to run: node(js)  the script

```js
var aa = new Date();
console.log(aa);
```

but the result is always show : 

```js
'bash' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
[Finished in 0.138s]
```

**Comment by danielbayley** [comment] 2017-10-13 01:52
Duplicate of [@Niefee see] #1449. Fixed in #1451.

**Closed by danielbayley** 2017-10-13 01:52 UTC

**Comment by Niefee** [comment] 2017-10-13 02:05
thinks
