### ISSUE TITLE
Add File Based support for C++

### ISSUE THREAD

**Issue by simkieu** [rgbkrk/atom-script#773] opened 2016-02-03 04:43 UTC
##### Platform: `linux`
---

**Comment by simkieu** [comment] 2016-02-03 04:43
#include <iostream>
using namespace std;

int main() {
	cout << "hello world" << endl;
	return 0;
}
cannot compile

**Comment by EntilZha** [comment] 2016-02-12 07:19
Duplicate of #558, could you post example there instead (oldest issue is canonical issue)?

**Closed by EntilZha** 2016-02-12 07:19 UTC
