### ISSUE TITLE
Uncaught TypeError: Cannot read property 'remove' of undefined

### ISSUE THREAD

**Issue by HorselessName** [rgbkrk/atom-script#1995] opened 2019-11-08 20:24 UTC
` C:\Users\Raul\.atom\packages\script\node_modules\atom-message-panel\lib\MessagePanelView.js:189
`

```
` TypeError:` Cannot read property 'remove' of undefined
    at ScriptView.MessagePanelView.remove (C:\Users\Raul\.atom\packages\script\node_modules\atom-message-panel\lib\MessagePanelView.js:189:30)
    at ScriptView.detach (C:\Users\Raul\.atom\packages\atom-beautify\node_modules\jquery\dist\jquery.js:5357:15)
    at ScriptView.removePanel (file:///C:/Users/Raul/.atom/packages/script/lib/script-view.js:89:10)
    at Object.closeScriptViewAndStopRunner (file:///C:/Users/Raul/.atom/packages/script/lib/script.js:161:21)
    at HTMLElement.scriptCloseView (file:///C:/Users/Raul/.atom/packages/script/lib/script.js:94:39)
    at CommandRegistry.handleCommandEvent (C:\Users\Raul\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:349392)
    at CommandRegistry.dispatch (C:\Users\Raul\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:347867)
    at ScriptView.close (file:///C:/Users/Raul/.atom/packages/script/lib/script-view.js:99:19)
    at HTMLDivElement.<anonymous> (C:\Users\Raul\.atom\packages\atom-beautify\node_modules\space-pen\lib\space-pen.js:220:36)
    at HTMLDivElement.dispatch (C:\Users\Raul\.atom\packages\atom-beautify\node_modules\jquery\dist\jquery.js:4435:9)
    at HTMLDivElement.elemData.handle `(C:\Users\Raul\.atom\packages\atom-beautify\node_modules\jquery\dist\jquery.js:4121:28)`

```

**Comment by HorselessName** [comment] 2019-11-08 20:24
`C:\Users\Raul.atom\packages\script\node_modules\atom-message-panel\lib\MessagePanelView.js:189

TypeError: Cannot read property 'remove' of undefined
at ScriptView.MessagePanelView.remove (C:\Users\Raul.atom\packages\script\node_modules\atom-message-panel\lib\MessagePanelView.js:189:30)
at ScriptView.detach (C:\Users\Raul.atom\packages\atom-beautify\node_modules\jquery\dist\jquery.js:5357:15)
at ScriptView.removePanel (file:///C:/Users/Raul/.atom/packages/script/lib/script-view.js:89:10)
at Object.closeScriptViewAndStopRunner (file:///C:/Users/Raul/.atom/packages/script/lib/script.js:161:21)
at HTMLElement.scriptCloseView (file:///C:/Users/Raul/.atom/packages/script/lib/script.js:94:39)
at CommandRegistry.handleCommandEvent (C:\Users\Raul\AppData\Local\atom\app-1.41.0\resources\app\static<embedded>:11:349392)
at CommandRegistry.dispatch (C:\Users\Raul\AppData\Local\atom\app-1.41.0\resources\app\static<embedded>:11:347867)
at ScriptView.close (file:///C:/Users/Raul/.atom/packages/script/lib/script-view.js:99:19)
at HTMLDivElement. (C:\Users\Raul.atom\packages\atom-beautify\node_modules\space-pen\lib\space-pen.js:220:36)
at HTMLDivElement.dispatch (C:\Users\Raul.atom\packages\atom-beautify\node_modules\jquery\dist\jquery.js:4435:9)
at HTMLDivElement.elemData.handle (C:\Users\Raul.atom\packages\atom-beautify\node_modules\jquery\dist\jquery.js:4121:28)

`

**Comment by HorselessName** [comment] 2019-11-08 20:25
The error happened when i tried to press X

**Comment by mahipaljyani** [comment] 2019-11-09 08:26
same error happens to me, did you find the answer?

**Comment by Quaintgoldenlion** [comment] 2019-11-09 12:02
Its also happening to me try contacting the developer bout the problem dont forget the details

**Comment by rotcelloCehT** [comment] 2019-11-09 16:37
I am having the same issue when pressing x

**Comment by Adespinoza** [comment] 2019-11-09 17:27
Can also confirm this issue happens when pressing 'x'

**Comment by pytommaso** [comment] 2019-11-09 18:08
to me when pressing ESC button

**Comment by burstWizard** [comment] 2019-11-10 02:49
also happened when pressing esc key

**Comment by thatrandomguyagain** [comment] 2019-11-10 06:37
happening when I press X

**Comment by terran5992** [comment] 2019-11-10 08:40
Im having the same problem as well when i try to close the window

**Comment by UltraVioletCoin** [comment] 2019-11-10 23:39
same problem when pressing x

**Comment by wjandrea** [comment] 2019-11-11 03:26
Duplicate of #1984

**Comment by arcleise** [comment] 2019-11-11 04:24
Same issue when pressing ESC

**Comment by PhilippePerret** [comment] 2019-11-11 05:28
Same issue when pressing ESC and X

**Comment by harrysentonbury** [comment] 2019-11-11 12:48
ditto, bit i can't complain, its the only editor of its kind that works in linux on a 13 year old laptop.

**Comment by HorselessName** [comment] 2019-11-12 14:26
Well, i uninstalled it since i could'nt figure it out how to make it work...
Not using script anymore, for those who use Python i suggest atom-python-run package

Will use 'script' again when this problem is fixed

**Comment by HorselessName** [comment] 2019-11-12 14:31
> Duplicate of #1984

The error there was fixed by a user commit, but as of this moment, it looks like it's happening again...
I'm using atom-python-run and platform-ide-terminal for now...

**Comment by Prince-let** [comment] 2019-11-13 11:25
When I press the button X , it occurs.
When I press the button X repeatly , it occurs all over the screen

**Comment by wjandrea** [comment] 2019-11-13 21:28
> > Duplicate of #1984
> 
> The error there was fixed by a user commit, but as of this moment, it looks like it's happening again...
> I'm using atom-python-run and platform-ide-terminal for now...

It was supposedly fixed, but there's some conflicting info. Even the author is saying the issue seems to be in `script`. Also [that PR](https://github.com/tcarlsen/atom-message-panel/pull/90) is still open and #1984 is still open.

I reverted to the previous version of `script` with `apm install script@3.18`

**Closed** 2020-04-23 15:02 UTC
