### ISSUE TITLE
Add support for HTML

### ISSUE THREAD

**Issue by yask123** [rgbkrk/atom-script#737] opened 2016-01-15 09:19 UTC
On pressing CMD+I , it should open browser

**Comment by SamStrawbridge** [comment] 2016-01-15 19:04
I may be wrong (and someone please correct me if I am), but seems out of script's ball park, would a package like https://github.com/gabceb/atom-web-view not better suit your requirement?  Was there a particular use case you had in mind?

**Comment by yask123** [comment] 2016-01-18 10:54
Yea, it does suit my requirement and I am currently using it. It would be nice it this feature was integrated in this extension only.

**Comment by EntilZha** [comment] 2016-02-12 07:46
Marking as duplicate of #330 and/or #724, there is a similar discussion there

**Closed by EntilZha** 2016-02-12 07:46 UTC
