### ISSUE TITLE
Input in Python not working

### ISSUE THREAD

**Issue by adamsloma** [rgbkrk/atom-script#511] opened 2015-07-21 03:38 UTC
I'm learning to use python and I made a little script that asks for input. When I run it, it takes forever and never actually shows anything. Here is a screenshot:

![screen shot 2015-07-20 at 8 37 58 pm](https://cloud.githubusercontent.com/assets/7192021/8792690/39170eda-2f1f-11e5-9234-e1c277bccd98.png)

**Comment by rgbkrk** [comment] 2015-07-26 19:02
We don't handle STDIN. If you want that, try out [Hydrogen](https://github.com/willwhitney/hydrogen).

Closing as duplicate of https://github.com/rgbkrk/atom-script/issues/385.

**Closed by rgbkrk** 2015-07-26 19:02 UTC

**Comment by nashatalani** [comment] 2019-01-28 04:00
Hi
I am using Atom to learn Python
the input is not working as the example below,
name = input ("Enter name:")
print ("Hello " + name)

Any suggestions how to make work, please?
