### ISSUE TITLE
Add File Based support for C  

### ISSUE THREAD

**Issue by khanhle10** [rgbkrk/atom-script#603] opened 2015-10-01 23:37 UTC
##### Platform: `linux`
---File Based runner not available for C++.

If it should exist, add an issue on GitHub, or send your own pull request.

**Comment by rgbkrk** [comment] 2015-10-18 04:33
Currently this works on OS X using `xcrun`. How would it work for Linux? C isn't interpreted, so we'd have to do some light trickery to build and run `a.out` I suppose.

**Comment by khanhle10** [comment] 2015-10-18 07:25
Alright thank you.


________________________________

**Comment by EntilZha** [comment] 2016-02-12 07:17
Duplicate of #454

**Closed by EntilZha** 2016-02-12 07:17 UTC
