### ISSUE TITLE
python prompt

### ISSUE THREAD

**Issue by ImAWizardLizard** [rgbkrk/atom-script#518] opened 2015-07-29 07:25 UTC
i am running my python file and it asks the user for a prompt but i am unable to enter an input in the atom text editor

**Comment by rgbkrk** [comment] 2015-07-29 14:59
We'd need someone to implement reading from STDIN.

Duplicate of #385.

**Closed by rgbkrk** 2015-07-29 14:59 UTC

**Comment by ImAWizardLizard** [comment] 2015-08-13 11:41
thankyou
