### ISSUE TITLE
Add support for XML

### ISSUE THREAD

**Issue by jucasoliveira** [rgbkrk/atom-script#1065] opened 2016-09-01 13:10 UTC
Atom tried to run my ant-script, using "ctrl + shift + b" but couldn't be able to run it.
The message is:
` Command not configured for XML!Add an issue on GitHub or send your own Pull Request.^C `

**Comment by nixel2007** [comment] 2016-09-01 17:31
There is no support for 'ant' now.

**Comment by andyrichardson** [comment] 2016-10-28 09:58
Duplicate of #798

**Closed by andyrichardson** 2016-10-28 09:58 UTC
