### ISSUE TITLE
Add support for MATLAB

### ISSUE THREAD

**Issue by pedwards97** [rgbkrk/atom-script#771] opened 2016-02-03 00:30 UTC
How do I add the lines of code to the grammar file for script?

**Comment by EntilZha** [comment] 2016-02-12 07:27
Duplicate of #231, there is also some discussion there already. You might look at a just merged PR for how to add it https://github.com/rgbkrk/atom-script/pull/793/files

**Closed by EntilZha** 2016-02-12 07:27 UTC
